version: '3.8'

services:
  discovery-server:
    build:
      context: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - neocart-network
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka"]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    build:
      context: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server
    networks:
      - neocart-network
    environment:
      SPRING_APPLICATION_NAME: config-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  user-service:
    build:
      context: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-server
    networks:
      - neocart-network
    environment:
      SPRING_APPLICATION_NAME: user-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  cart-service:
    build:
      context: ./cart-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - config-server
    networks:
      - neocart-network
    environment:
      SPRING_APPLICATION_NAME: cart-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

  product-service:
    build:
      context: ./product-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - config-server
    networks:
      - neocart-network
    environment:
      SPRING_APPLICATION_NAME: product-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka/

networks:
  neocart-network:
    driver: bridge
