spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
cloud:
  config:
    import: configserver:http://localhost:8888  # Config Server URL
    fail-fast: true  # Fails if config server is not reachable
server:
  port: 8080
eureka:
  client:
    enabled: true
    use-dns-for-fetching-service-urls: false
    prefer-ip-address: true
    should-fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: "/yVxiGImzqTLIc/KZ6MaO7bL5EUl58NtkqgvEugu6AM="
  expiration: 3600000