spring:
  application:
    name: user-service
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  datasource:
    url: jdbc:mariadb://kautham.helioho.st:3306/kautham_ecomm?connectTimeout=10000&socketTimeout=15000
    username: kautham_user
    password: '${DB_PASSWORD}'
    driver-class-name: org.mariadb.jdbc.Driver

  hikari:
    maximum-pool-size: 2
    minimum-idle: 1
    idle-timeout: 30000
    max-lifetime: 60000
    keepalive-time: 30000
    connection-timeout: 10000
    validation-timeout: 5000
    initialization-fail-timeout: 0
    auto-commit: true
    connection-test-query: SELECT 1
    leak-detection-threshold: 20000

cloud:
  config:
    import: configserver:http://config-server:8888  # Config Server URL
    fail-fast: true  # Fails if config server is not reachable
server:
  port: 8080
eureka:
  client:
    enabled: true
    use-dns-for-fetching-service-urls: false
    prefer-ip-address: true
    should-fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://discovery-server-vu7l.onrender.com/eureka

jwt:
  secret: '${JWT_SECRET_KEY}'
  expiration: 3600000