spring:
  application:
    name: product-service
  config:
    import: optional:configserver:http://config-server:8888  # Config Server URL
    fail-fast: true  # Fails if config server is not reachable
  datasource:
    url: jdbc:mariadb://kautham.helioho.st:3306/kautham_ecomm?connectTimeout=10000&socketTimeout=15000
    username: kautham_product
    password: 6vm746Qs&
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 8081
eureka:
  client:
    enabled: true
    use-dns-for-fetching-service-urls: false
    prefer-ip-address: true
    should-fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: https://discovery-server-vu7l.onrender.com/eureka

jwt:
  secret: '${JWT_SECRET_KEY}'

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.jdbc.datasource.DriverManagerDataSource: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: ERROR
